export class addincentive {
  Consultant_Id:any;
  Recruiter_Id:any;
 Consultant_Name:any;
 Recruiter_Name:any;
 IncentiveType:any;
 Project_Start_Date:any; 
 Term1_IncentivePeriod:any;
 Term1_IncentivepayableDate:any; 
 Term1_IncentiveAmount:any;
 Is_Term1_IncentivePaid:any;
 Term2_IncentivePeriod:any;
 Term2_IncentivePayableDate:any; 
 Term2_IncentiveAmount:any;
 Is_Term2_IncentivePaid:any;
 Term3_IncentivePeriod:any;
 Term3_IncentivePayableDate:any; 
 Term3_IncentiveAmount:any;
 Is_Term3_IncentivePaid:any;
 Term4_IncentivePeriod:any;
 Term4_IncentivePayableDate:any; 
 Term4_IncentiveAmount:any;
 Is_Term4_IncentivePaid:any;
 Comments:any;
 Notes1:any;
 Notes2:any;
 Created_Date:any; 
 Created_by:any;
 Modified_Date:any;
 Modified_by:any;
 Incentive_Status:any; 
    
  }